spring:
  redis:
    port: 6379
    password: fordearme2018
    host: 127.0.0.1
    timeout: 1000
    jedis:
      pool:
        max-active: 10
        min-idle: 5
        max-idle: 10
        max-wait: 2000
  cache:
    type: redis
    cache-names: redisCache
server:
  port: 8081